import Link from "next/link";
import { use } from "react";
import Header from "../components/primitives/main-header";
import "./output.css";

const getUser = async (id: number) => {
  const user = await fetch(`https://jsonplaceholder.typicode.com/users/${id}`, {
    cache: "no-store",
  });
  return user.json();
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = use(getUser(1));

  return (
    <html lang="en" className="h-full w-full">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="w-full h-full">
        <Header />
        <div className="main-layout-children-wrapper flex">{children}</div>
        <nav className="flex justify-between items-center px-6 main-layout-footer">
          <Link href="/" className="cursor-pointer">
            <div>Logo</div>
          </Link>
          <Link href="/profile" className="cursor-pointer">
            {user.name}
          </Link>
        </nav>
      </body>
    </html>
  );
}

// the below code is ment to have a layout that has a minimum height of the remaining space between header and footer

// import Link from "next/link";
// import { use } from "react";
// import "./output.css";

// const getUser = async (id: number) => {
//   const user = await fetch(`https://jsonplaceholder.typicode.com/users/${id}`, {
//     cache: "no-store",
//   });
//   return user.json();
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   const user = use(getUser(1));

//   return (
//     <html lang="en" className="h-full w-full">
//       <head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </head>
//       <body className="min-h-full flex flex-col w-full">
//         <nav className="flex justify-between items-center px-6 main-layout-header sticky top-0">
//           <Link href="/" className="cursor-pointer">
//             <div>Logo</div>
//           </Link>
//           <Link href="/profile" className="cursor-pointer">
//             {user.name}
//           </Link>
//         </nav>
//         <div className="p-6 flex flex-1 main-layout-children-wrapper">
//           {children}
//         </div>
//         <nav className="flex justify-between items-center px-6 main-layout-footer">
//           <Link href="/" className="cursor-pointer">
//             <div>Logo</div>
//           </Link>
//           <Link href="/profile" className="cursor-pointer">
//             {user.name}
//           </Link>
//         </nav>
//       </body>
//     </html>
//   );
// }
